name: tugaspm3
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Tambahkan package shared_preferences untuk menangani penyimpanan lokal
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Jika kamu ingin menambahkan aset seperti gambar atau font, tambahkan di sini
  # assets:
  #   - images/

  # fonts:
  #   - family: SeventeenFont
  #     fonts:
  #       - asset: fonts/SeventeenFont-Regular.ttf
